Added rule builder to filter resources
elimuinformatics/hapi-fhir-jpaserver-starter pull request #25
Opened 2021-04-06 11:17 UTC by shubhamparikh927

2021-04-06 14:41 UTC, hankwallace commented on src/main/java/ca/uhn/fhir/jpa/starter/CustomAuthorizationInterceptor.java
> +		return new RuleBuilder().allow().read().allResources()
The formatting of this makes it a little confusing. The flow / pseudo-code is:
```
  .allowReadsInPatientCompartment().andThen()
  .allowWritesInPatientCompartment().andThen()
  .denyEverythingElse()
```

 Please change the code to:
```
return new RuleBuilder()
  .allow().read().allResources().inCompartment("Patient", new IdType("Patient", patientId)).andThen()
  .allow().write().allResources().inCompartment("Patient", new IdType("Patient", patientId)).andThen()
  .denyAll()
  .build();
```

2021-04-06 14:42 UTC, hankwallace requested changes
One minor code formatting change suggested.

2021-04-06 15:28 UTC, kevinliuelimu reviewed
I am good with the code changes. Please fix as Hank suggested.

2021-04-06 18:39 UTC, kevinliuelimu approved these changes

2021-04-08 13:54 UTC, hankwallace approved these changes

2021-04-09 05:22 UTC, merged