Removed client id validation from oauth token
elimuinformatics/hapi-fhir-jpaserver-starter pull request #35
Opened 2022-03-01 11:26 UTC by vsinghht

Remove client id verification from oauth 
Tested on local by running integration test

2022-03-01 14:38 UTC, shubhamparikh927 submitted a review, later dismissed

2022-03-01 14:44 UTC, hankwallace requested changes

2022-03-01 14:44 UTC, hankwallace commented on src/main/java/ca/uhn/fhir/jpa/starter/CustomAuthorizationInterceptor.java
> -			if (oAuth2Helper.verifyClientId(jwt, OAUTH_CLIENT_ID)) {
The indentation of the following lines needs to change now that the `if` has been removed.

2022-03-02 09:04 UTC, shubhamparikh927 approved these changes

2022-03-02 14:30 UTC, hankwallace approved these changes

2022-03-03 07:31 UTC, merged