Sync 6.1.0
elimuinformatics/hapi-fhir-jpaserver-starter pull request #38
Opened 2022-11-23 11:58 UTC by shubhamparikh927

2022-11-25 12:43 UTC, shubhamparikh927 commented
Tested by:

- Running code locally, verified with authentication
- Verified metadata endpoint (should send oauth details for R4)
- Tested by running DSTU2, DSTU3 and R4 version for the code.
- Checked consent and search narrow interseptor

2022-11-28 15:20 UTC, hankwallace requested changes
A few comments on changes and a bigger question on the custom application configuration file. Done with my review for now.

2022-11-28 15:20 UTC, hankwallace commented on src/main/resources/application.yaml
> +#Adds the option to go to eg. http://localhost:8080/actuator/health for seeing the running configuration
Did you review each of the changes here and apply the ones that make sense to our custom configuration file?

2022-11-28 15:20 UTC, hankwallace commented on src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR4IT.java
> +import org.hl7.fhir.r4.model.Person;
Why are there differences in this file between this and the upstream repo?

2022-11-28 15:20 UTC, hankwallace commented on src/test/java/ca/uhn/fhir/jpa/starter/ExampleServerR5IT.java
> -	  "spring.main.allow-bean-definition-overriding=true"
Why are there differences in this file between this and the upstream repo?

2022-11-28 15:20 UTC, hankwallace commented on src/test/java/ca/uhn/fhir/jpa/starter/MultitenantServerR4IT.java
> -	  "spring.main.allow-bean-definition-overriding=true"
Why are there differences in this file between this and the upstream repo?

2022-11-28 15:20 UTC, hankwallace commented on src/test/java/ca/uhn/fhir/jpa/starter/MultitenantServerR4IT.java
> -
Why are there differences in this file between this and the upstream repo?

2022-11-30 20:51 UTC, hankwallace requested changes

2022-11-30 20:51 UTC, hankwallace commented on src/main/resources/application-custom.yaml
> +    allow-bean-definition-overriding: true
please double-check all of the changes to the `application.yaml` file. this line is commented-out in the upstream repo.

2022-12-01 17:25 UTC, hankwallace requested changes

2022-12-01 17:25 UTC, hankwallace commented on src/main/resources/application-custom.yaml
>        hibernate.search.backend.type: lucene
Since we have search disabled, I think we should comment-out all of `hibernate.search.*` settings on lines 41-45.

2022-12-01 17:50 UTC, hankwallace approved these changes

2022-12-02 10:20 UTC, merged